# 🚀 3D Cellular Neural Network - Main Configuration
# =================================================
# Современная конфигурация для динамической архитектуры

# === PROJECT METADATA ===
project:
  name: "3D Cellular Neural Network"
  version: "4.0.0"
  description: "3D клеточная нейронная сеть с биологической архитектурой"
  architecture_type: "dynamic_cellular_network"

# === DYNAMIC CONFIGURATION SYSTEM ===
# Эти значения используются как fallback, основная конфигурация создается динамически
dynamic_config:
  enable: true
  mode: "auto" # auto, development, research, validation, production
  auto_hardware_detection: true

# === BASIC LATTICE CONFIGURATION (FALLBACK) ===
# PHASE 4 UPDATE: Обновлены fallback значения для соответствия clean конфигурациям
lattice:
  xs: 16 # PHASE 4: 16×16×16 вместо 20×20×10
  ys: 16
  zs: 16
  total_neurons: 4096 # 16×16×16 = 4096
  connectivity: "26-neighbors" # PHASE 4: 26 neighbors вместо 6

# === EMBEDDING CONFIGURATION ===
embeddings:
  embedding_dim: 768
  teacher_model: "distilbert-base-uncased"
  normalization: true

# === TRAINING CONFIGURATION ===
training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
  optimizer: "AdamW"
  scheduler: "ReduceLROnPlateau"

# === GMLP CONFIGURATION (FALLBACK) ===
# PHASE 4 UPDATE: Обновлены для hybrid NCA+gMLP архитектуры
gmlp:
  state_size: 8 # PHASE 4: 8 для совместимости с NCA
  neighbor_count: 26 # PHASE 4: 26 neighbors (3D Moore neighborhood)
  hidden_dim: 32 # Динамически: 32-332 в зависимости от scale
  external_input_size: 12 # Динамически: 12-62 в зависимости от scale
  memory_dim: 16 # Динамически: 16-116 в зависимости от scale
  use_memory: false # PHASE 4: false для экономии памяти
  activation: "gelu"
  dropout: 0.1

# === NCA CONFIGURATION (ЦЕНТРАЛИЗОВАННАЯ) ===
# PHASE 4: Единый источник истины для всех NCA параметров
nca:
  enabled: true # PHASE 4: Включено для hybrid архитектуры
  state_size: 4 # ЦЕНТРАЛИЗОВАННО: 4 для минимальной NCA
  hidden_dim: 3 # ЦЕНТРАЛИЗОВАННО: 3 для минимальной NCA
  external_input_size: 1 # ЦЕНТРАЛИЗОВАННО: 1 для минимальной NCA
  neighbor_count: 26 # ЦЕНТРАЛИЗОВАННО: 26 для 3D Moore neighborhood
  target_params: 69 # ЦЕНТРАЛИЗОВАННО: Целевое количество параметров
  activation: "tanh" # ЦЕНТРАЛИЗОВАННО: tanh для стабильности NCA

# === MINIMAL NCA CELL CONFIGURATION (ДЛЯ СОВМЕСТИМОСТИ) ===
# Дублируем NCA параметры в формате ожидаемом lattice и другими модулями
minimal_nca_cell:
  state_size: 3
  neighbor_count: 26
  hidden_dim: 4
  external_input_size: 1
  activation: "tanh"
  dropout: 0.0
  use_memory: false
  enable_lattice_scaling: false
  target_params: 69

# === DEVICE CONFIGURATION ===
device:
  use_gpu: true
  gpu_device: "cuda:0"
  fallback_to_cpu: true
  mixed_precision: true

# === DATA PATHS ===
data:
  embeddings_dir: "data/embeddings"
  checkpoints_dir: "checkpoints"
  logs_dir: "logs"

# === LOGGING ===
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/main.log"
  log_to_console: true

# === TEACHER MODELS ===
teacher_models:
  primary_model: "distilbert-base-uncased"
  fallback_models:
    - "sentence-transformers/all-MiniLM-L6-v2"
    - "roberta-base"

# === BIOLOGICAL PRINCIPLES ===
biological:
  # Клетки как нейроны с общими весами
  shared_weights: true

  # Решетка как нервная ткань
  tissue_simulation: true

  # Рецепторная стратегия (8-12% покрытия)
  receptor_coverage: 0.1

  # Сигналы как нервные импульсы
  signal_propagation: true
  propagation_steps: 10

# === EXPERIMENTAL FEATURES ===
experimental:
  enable_nca: true
  enable_spatial_attention: false
  enable_multi_teacher: false
  debug_mode: false

# === PHASE 4 ADDITIONS ===
# Новые секции для поддержки clean конфигураций

# Пластичность (из clean конфигураций)
plasticity:
  enable_plasticity: true
  plasticity_rule: "combined" # STDP + BCM + competitive
  enable_competitive_learning: true
  enable_metaplasticity: true
  enable_clustering: false # Пока отключено

# Оптимизация памяти
optimization:
  memory_efficient: true
  use_checkpointing: true
  mixed_precision: true
