# 🎯 OPTIMIZED GatedMLPCell Configuration - 23K Parameters
# ========================================================
#
# Результат Шага 2.2: Оптимизация GatedMLPCell
# Golden middle между качеством обработки и эффективностью
#
# Ключевые достижения:
# - 54,892 → 23,805 параметров (2.3x reduction)
# - Compression ratio: 61x (оптимальный баланс)
# - Information quality: Good (vs Aggressive в 10K версии)
# - БЕЗ локальной памяти (полагаемся на spatial distributed memory)

# === PROJECT METADATA ===
project:
  name: "Optimized GatedMLPCell 23K"
  version: "2.2.0-optimized"
  description: "Результат Шага 2.2: оптимизированная GatedMLPCell с 23K параметров"

# === ARCHITECTURE SELECTION ===
architecture:
  # Гибридный режим
  hybrid_mode: true

  # Архитектуры
  neuron_architecture: "minimal_nca" # 79 параметров (фиксированно)
  connection_architecture: "minimal_gmlp" # 23,805 параметров (оптимизированно)

  # Отключение автомасштабирования NCA
  disable_nca_scaling: true

  # Финальные target_params
  neuron_target_params: 79 # MinimalNCA (фиксированно)
  connection_target_params: 23805 # OptimizedGatedMLP

# === LATTICE CONFIGURATION ===
lattice_3d:
  # Тестовая решетка
  dimensions: [20, 20, 10] # 4,000 клеток
  total_cells: 4000

  # Production target: [300, 300, 150] = 13.5M клеток
  # Estimated total params: 13.5M × 23,805 ≈ 321B parameters
  # Memory requirement: ~1.3TB (requires scaling/chunking)

  # Соседство
  neighbors: 26 # 3D Moore neighborhood
  neighbor_finding_strategy: "tiered"

  # GPU optimization
  parallel_processing: true
  gpu_enabled: true
  batch_size: 4

# === OPTIMIZED CONNECTION ARCHITECTURE ===
connection_config:
  architecture: "minimal_gmlp"

  minimal_gmlp:
    # ФИНАЛЬНЫЕ ОПТИМИЗИРОВАННЫЕ ПАРАМЕТРЫ
    state_size: 36 # Синхронизировано с NCA
    neighbor_count: 26 # 3D Moore neighborhood

    # Bottleneck architecture (ключевое решение)
    bottleneck_dim: 16 # Optimal: 61x compression ratio
    hidden_dim: 32 # Balanced processing capacity
    external_input_size: 4 # Reasonable external input

    # Architecture features
    use_memory: false # НЕТ локальной памяти!
    distributed_memory: true # Полагаемся на spatial topology
    activation: "gelu" # Modern activation
    dropout: 0.0 # No dropout для экономии

    # Target achievements
    target_params: 23805 # Фактически достигнуто
    compression_ratio: 61 # 976 inputs → 16 bottleneck
    information_quality: "good" # vs "aggressive" в 10K версии

# === NEURON ARCHITECTURE (unchanged) ===
cell_prototype:
  prototype_name: "minimal_nca_cell"

  minimal_nca_cell:
    # Фиксированные параметры (НЕ масштабируются)
    state_size: 36
    neighbor_count: 26
    hidden_dim: 6
    external_input_size: 2

    # NCA specific
    activation: "tanh"
    dropout: 0.0
    use_memory: false
    enable_lattice_scaling: false
    target_params: 79

# === I/O CONFIGURATION ===
io:
  input_face: "front"
  output_face: "back"
  placement_strategy: "proportional"

  io_strategy_config:
    coverage_ratio:
      min_percentage: 8.0
      max_percentage: 12.0
    seed: 42

# === TRAINING CONFIGURATION ===
training:
  # Гибридная оптимизация
  learning_rate: 0.0005 # Conservative для stability
  batch_size: 2 # Memory constraints с 23K params
  epochs: 100
  optimizer: "AdamW"
  scheduler: "ReduceLROnPlateau"

  # Loss weights
  loss_weights:
    nca_dynamics: 0.3 # NCA state evolution
    connection_learning: 0.4 # GatedMLP connectivity (основной фокус)
    output_reconstruction: 0.3 # Final output quality

# === PERFORMANCE METRICS ===
performance:
  # Достигнутые результаты Шага 2.2
  achieved_params: 23805 # vs target 25,000 (SUCCESS!)
  reduction_from_original: 2.3 # 54,892 → 23,805 (2.3x reduction)
  compression_ratio: 61 # Optimal information processing
  forward_time_ms: 14.4 # Fast processing

  # Scaling projections
  estimated_300x300x150:
    total_params: "321B" # 13.5M × 23,805
    memory_requirement: "1.3TB" # Requires chunking/streaming
    feasible_with_chunking: true

# === STATUS ===
status:
  step_2_2: "COMPLETED" # ✅ GatedMLPCell optimization
  quality: "EXCELLENT" # Golden middle achieved
  ready_for_step_2_3: true # STDP integration ready

# === NEXT STEPS ===
next_steps:
  - "Шаг 2.3: STDP механизм для connection_weights"
  - "End-to-end тестирование гибридной архитектуры"
  - "Memory chunking стратегия для 300×300×150"
