# 🔧 UNIVERSAL ADAPTER EXAMPLES
# Примеры конфигураций для разных сценариев использования

# === CURRENT PROJECT SETUP ===
current_project:
  cube_dimensions: [15, 15, 11]
  surface_size: 225 # 15×15

  # Meta-Llama-3-8B → 15×15 surface
  llama3_adapter:
    teacher_model: "Meta-Llama-3-8B"
    input_dim: 4096
    output_dim: 225
    strategy: "learned_linear"
    compression_ratio: 0.055 # 225/4096 = 5.5%

  # DistilBERT → 15×15 surface (для сравнения)
  distilbert_adapter:
    teacher_model: "DistilBERT"
    input_dim: 768
    output_dim: 225
    strategy: "learned_linear"
    compression_ratio: 0.293 # 225/768 = 29.3%

# === FUTURE EXPERIMENT SCENARIOS ===

# Experiment 1: Larger cube для better capacity
experiment_larger_cube:
  cube_dimensions: [20, 20, 15]
  surface_size: 400 # 20×20

  llama3_adapter:
    input_dim: 4096
    output_dim: 400
    strategy: "hierarchical"
    compression_ratio: 0.098 # 400/4096 = 9.8%

# Experiment 2: Different teacher models
experiment_different_teachers:
  cube_dimensions: [15, 15, 11]
  surface_size: 225

  adapters:
    llama3_8b:
      input_dim: 4096
      compression_ratio: 0.055

    llama3_70b:
      input_dim: 8192
      compression_ratio: 0.027 # Much stronger compression

    bert_large:
      input_dim: 1024
      compression_ratio: 0.220

    openai_embedding:
      input_dim: 1536
      compression_ratio: 0.146

# Experiment 3: Multi-surface approaches
experiment_multi_surface:
  cube_dimensions: [15, 15, 11]
  surface_configurations:
    single_surface:
      surfaces: 1
      surface_size: 225
      total_io: 225

    triple_surface:
      surfaces: 3 # front, back, top
      surface_size: 225
      total_io: 675 # 3×225

    full_surface:
      surfaces: 6 # all faces
      surface_size: 225
      total_io: 1350 # 6×225

# === STRATEGY COMPARISONS ===
strategy_analysis:
  # LLaMA-3 4096D → 225D surface
  compression_strategies:
    learned_linear:
      parameters: 921600 # 4096×225 + 225×4096
      complexity: "low"
      training_time: "fast"

    hierarchical:
      intermediate_layers: [2048, 1024, 512]
      parameters: ~1500000
      complexity: "medium"
      training_time: "medium"

    attention_based:
      attention_heads: 8
      parameters: ~2000000
      complexity: "high"
      training_time: "slow"

    autoencoder:
      bottleneck_dim: 128
      parameters: ~1200000
      complexity: "medium"
      training_time: "medium"

# === PRACTICAL CONFIGURATIONS ===

# Configuration A: Research focus - максимальная информация
research_config:
  strategy: "hierarchical"
  reconstruction_loss_weight: 0.3
  target_preservation: 0.95 # 95% information preservation
  acceptable_parameters: 2000000 # Up to 2M params for adapter

# Configuration B: Production focus - efficiency
production_config:
  strategy: "learned_linear"
  reconstruction_loss_weight: 0.1
  target_preservation: 0.85 # 85% preservation acceptable
  acceptable_parameters: 1000000 # Max 1M params for adapter

# Configuration C: Memory constrained
memory_constrained_config:
  strategy: "learned_linear"
  reconstruction_loss_weight: 0.05
  target_preservation: 0.75 # Accept lower preservation
  acceptable_parameters: 500000 # Max 500K params

# === EXPECTED OUTCOMES ===
expected_results:
  # Information preservation rates
  preservation_rates:
    learned_linear: 0.85 # 85% информации сохраняется
    hierarchical: 0.92 # 92% информации сохраняется
    attention_based: 0.90 # 90% информации сохраняется
    autoencoder: 0.88 # 88% информации сохраняется

  # Training convergence
  convergence_epochs:
    learned_linear: 10 # Fast convergence
    hierarchical: 20 # Medium convergence
    attention_based: 30 # Slow convergence
    autoencoder: 25 # Medium-slow convergence

  # Parameter efficiency (performance per parameter)
  efficiency_scores:
    learned_linear: 9.2 # High efficiency
    hierarchical: 7.8 # Medium efficiency
    attention_based: 6.5 # Lower efficiency
    autoencoder: 7.2 # Medium efficiency

# === IMPLEMENTATION ROADMAP ===
implementation_phases:
  phase_1_basic:
    goal: "Get learned_linear working"
    models: ["Meta-Llama-3-8B", "DistilBERT"]
    cube_sizes: [[15, 15, 11]]
    duration: "1 week"

  phase_2_optimization:
    goal: "Test different strategies"
    strategies: ["learned_linear", "hierarchical"]
    optimization_focus: "reconstruction_loss"
    duration: "2 weeks"

  phase_3_scaling:
    goal: "Test different models and cube sizes"
    models: ["Meta-Llama-3-8B", "Meta-Llama-3-70B", "BERT-large"]
    cube_sizes: [[15, 15, 11], [20, 20, 15], [12, 12, 8]]
    duration: "2 weeks"

  phase_4_production:
    goal: "Production-ready adapter manager"
    features: ["auto-detection", "config-driven", "model-agnostic"]
    duration: "1 week"

# === SUCCESS METRICS ===
success_criteria:
  adapter_quality:
    min_reconstruction_accuracy: 0.80 # 80% reconstruction
    max_information_loss: 0.25 # Max 25% loss
    max_additional_parameters: 2000000 # Max 2M params overhead

  system_integration:
    cube_training_improvement: 0.10 # +10% Q→A similarity
    training_stability: 0.95 # 95% stable runs
    inference_speed_overhead: 0.20 # Max 20% slowdown

  flexibility:
    supported_models: 5 # At least 5 different models
    supported_cube_sizes: 3 # At least 3 different sizes
    auto_configuration: true # Automatic size detection
