# Тестовая конфигурация для демонстрации гибридной стратегии поиска соседей.
# Использует 6 локальных соседей и 20 случайных.

# ==================================
# Секция Решетки (Lattice)
# ==================================
lattice:
  dimensions: [10, 10, 10] # Небольшая решетка для теста
  boundary_conditions: "periodic" # Тороидальная решетка, чтобы у всех было одинаковое число локальных соседей

  # --- Новая конфигурация топологии ---
  neighbors: 26 # Общее число соседей = 6 (local) + 20 (random)
  neighbor_finding_strategy: "hybrid" # Используем новую гибридную стратегию
  neighbor_strategy_config:
    local_count: 6
    random_count: 20

  cache_neighbors: true # Кэшируем соседей для производительности
  seed: 42 # Для воспроизводимости случайной выборки

# ==================================
# Секция Клетки (Cell)
# ==================================
cell:
  # Используем gMLP, так как он лучше всего подходит для обработки большого числа соседей
  prototype_name: "gmlp"

  # --- Параметры gMLP клетки ---
  gmlp_cell:
    state_size: 32
    neighbor_count: 26 # ВАЖНО: должно совпадать с lattice.neighbors
    hidden_dim: 128
    use_memory: true
    target_params: 25000

# ==================================
# Секция I/O
# ==================================
io:
  input_face: "front"
  output_face: "back"
  placement_strategy: "proportional"
  io_strategy_config:
    coverage_ratio:
      min_percentage: 10.0
      max_percentage: 20.0
    seed: 42 # Отдельный сид для размещения I/O для независимости
