# 🚀 3D Cellular Neural Network - Main Configuration
# =================================================
# Современная конфигурация для динамической архитектуры

# === PROJECT METADATA ===
project:
  name: "3D Cellular Neural Network"
  version: "4.0.0"
  description: "3D клеточная нейронная сеть с биологической архитектурой"
  architecture_type: "dynamic_cellular_network"

# === DYNAMIC CONFIGURATION SYSTEM ===
# Эти значения используются как fallback, основная конфигурация создается динамически
dynamic_config:
  enable: true
  mode: "auto" # auto, development, research, validation, production
  auto_hardware_detection: true

# === BASIC LATTICE CONFIGURATION (FALLBACK) ===
# Динамическая система переопределит эти значения
lattice:
  xs: 10
  ys: 10
  zs: 8
  total_neurons: 800
  connectivity: "6-neighbors"

# === EMBEDDING CONFIGURATION ===
embeddings:
  embedding_dim: 768
  teacher_model: "distilbert-base-uncased"
  normalization: true

# === TRAINING CONFIGURATION ===
training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
  optimizer: "AdamW"
  scheduler: "ReduceLROnPlateau"

# === GMLP CONFIGURATION (FALLBACK) ===
# Динамическая система создает правильные значения в зависимости от scale
gmlp:
  state_size: 32
  neighbor_count: 6
  hidden_dim: 32 # Динамически: 32-332 в зависимости от scale
  external_input_size: 12 # Динамически: 12-62 в зависимости от scale
  memory_dim: 16 # Динамически: 16-116 в зависимости от scale
  use_memory: true
  activation: "gelu"
  dropout: 0.1

# === DEVICE CONFIGURATION ===
device:
  use_gpu: true
  gpu_device: "cuda:0"
  fallback_to_cpu: true
  mixed_precision: true

# === DATA PATHS ===
data:
  embeddings_dir: "data/embeddings"
  checkpoints_dir: "checkpoints"
  logs_dir: "logs"

# === LOGGING ===
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/main.log"
  log_to_console: true

# === TEACHER MODELS ===
teacher_models:
  primary_model: "distilbert-base-uncased"
  fallback_models:
    - "sentence-transformers/all-MiniLM-L6-v2"
    - "roberta-base"

# === BIOLOGICAL PRINCIPLES ===
biological:
  # Клетки как нейроны с общими весами
  shared_weights: true

  # Решетка как нервная ткань
  tissue_simulation: true

  # Рецепторная стратегия (8-12% покрытия)
  receptor_coverage: 0.1

  # Сигналы как нервные импульсы
  signal_propagation: true
  propagation_steps: 10

# === EXPERIMENTAL FEATURES ===
experimental:
  enable_nca: true
  enable_spatial_attention: false
  enable_multi_teacher: false
  debug_mode: false
