# Конфигурация Cell Prototype - "Умной Клетки"

# === БАЗОВЫЕ РАЗМЕРЫ ===
cell_prototype:
  # Размеры входов и выходов
  input_size: 12 # Размер внешнего входа для граничных клеток
  state_size: 8 # Размер состояния клетки (и размер выхода)
  output_size: 8 # Размер выхода (обычно равен state_size)

  # Количество соседей для 3D решетки
  num_neighbors: 6 # В 3D пространстве: верх, низ, лево, право, вперед, назад

# === АРХИТЕКТУРА НЕЙРОСЕТИ ===
architecture:
  # Структура слоев
  hidden_layers: [16] # Размеры скрытых слоев (можно добавить больше: [16, 12])

  # Функция активации
  activation: "tanh" # Варианты: "tanh", "sigmoid", "relu"
  output_activation: "tanh" # Выходная активация (фиксирована для стабильности)

  # Параметры слоев
  use_bias: true # Использовать смещения в линейных слоях
  dropout: 0.0 # Dropout для регуляризации (0.0 = выключен)

# === ИНИЦИАЛИЗАЦИЯ ВЕСОВ ===
initialization:
  method: "xavier_uniform" # Метод инициализации весов
  bias_init: "zeros" # Инициализация смещений

# === ПАРАМЕТРЫ ДЛЯ ОТЛАДКИ ===
debug:
  # Проверки входных данных
  validate_inputs: true # Проверять размерности входов
  check_gradients: false # Проверять градиенты (для отладки обучения)

  # Логирование
  log_level: "INFO" # Уровень логирования
  log_forward_pass: false # Логировать каждый forward pass

# === ОГРАНИЧЕНИЯ И ПРОВЕРКИ ===
constraints:
  # Ограничения на выходные значения
  output_range: [-1.0, 1.0] # Диапазон выходных значений

  # Проверки стабильности
  max_gradient_norm: 1.0 # Максимальная норма градиента
  check_nan_inf: true # Проверять NaN и Inf в выходах
